name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Set up node
        run: sudo apt-get -y -q install npm

      - name: Install morphir-elm
        run: npm install -g morphir-elm

      - name: Compile morphir implementation
        run: mvn -B -ntp clean test
